spring:
  rabbitmq:
    queue:
      name: ${QUEUE_NAME:payments}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  application:
    name: zuppay-processor
  jpa:
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgresql
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/zuppay}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWD:postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
